### DISCUSSION TITLE
Github workflows - using multiple methods to create testing

### DISCUSSION THREAD

**Discussion by Trogdor-007** [projen/projen#2096] [General]
I've been using projen for a few months now and the only issues I get is when having to modify other files with ".projenrc.js". I have gotten better at utilizing the API documentation but currently, I'm kinda stuck (spent a few hours already).

Issue: I'd like to have my tests run every time I do a Pull Request.

Solution: I have tried using the "new github.GithubWorkflow" documentation but I can only seem to either use the ".addJob" OR the ".on" methods (https://projen.io/api/API.html#projen-github-githubworkflow). I am pretty much re-creating the default workflow of "pull-request-lint.yml" but adding an additional step. I wanted this to be an entirely new workflow but can't seem to get it to work.

I'd like to create the workflow .yml file to the following (in this case 'run-tests.yml):

```
name: Run-Tests
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - ready_for_review
      - edited
jobs:
  Run Tests:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Test
        run: npm run test
```

I can either the above but only in 2 separate parts. Either I create the 1st half (up until jobs) or the 2nd half from jobs onward.
```
new github.GithubWorkflow(project.github, 'Run-Tests').addJob('Run Tests', {
  runsOn: 'ubuntu-latest',
  permissions: {
    pullRequests: 'write',
  },
  steps: [
    {
      name: 'Test',
      run: 'npm run test',
    }
  ],
});

```

And this:
```
new github.GithubWorkflow(project.github, 'Run-Tests').on({
  pullRequestTarget: {
    types: [
      'opened',
      'synchronize',
      'reopened',
      'labeled',
      'ready_for_review',
      'edited',
    ]
  },
});
```

The issue is I can't run both and I don't know how to run the first and then add the second to the file. I tried setting one of them to a const and then tried seeing if I could call the 2nd method but that doesn't work at all since the "GithubWorkflow" class won't let me call any of the methods unless its a NEW instance of the class.

I am pretty new to development in Typescript (formerly Python) and pretty sure this is a Layer 8 issue so any help with this is greatly appreciated.
