### DISCUSSION TITLE
Python - poetry

### DISCUSSION THREAD

**Discussion by thoroc** [projen/projen#2901] [Q&A] [answered]
Is there an escape hatch for poetry - python project? 

I am trying to add several different deps but none show in the `pyproject.toml` file:

within declaring the project object:
```python
project = PythonProject(
    ...,
    poetry=True,
    version="0.1.0",
    pytest=True,
    version="0.1.0",
    dev_deps=["pytest-cov", "pytest-mock", "pytest-clarity"]
)
```

after declaring the project object:
```python
project.add_dev_dependency("pytest-cov")
project.add_dev_dependency("pytest-mock")
project.add_dev_dependency("pytest-clarity")
```

But neither are installing the dependencies: neither present in the `pyproject.toml` file nor in the `.venv/lib/` directory.

I have tried also to add an override as follow:

```python

project_config = project.try_find_object_file("pyproject.toml")
project_config.add_override("tool.poetry.dev-dependencies", "pytest")
```

But that mangled the `pyproject.toml` file from:

```toml
[tool.poetry]
...
readme = "README.md"

  [tool.poetry.dependencies]
  python = "^3.7"

  [tool.poetry.dev-dependencies]
  projen = "0.73.3"
```

to this:

```toml
[tool.poetry]
...
readme = "README.md"
dev-dependencies = [ "pytest", "pytest-cov", "pytest-mock", "pytest-clarity" ]

  [tool.poetry.dependencies]
  python = "^3.7"
```
