### ISSUE TITLE
Github action CANNOT mount volume when running steps in a "jsii/superchain" container 

### ISSUE THREAD

**Issue by wchaws** [projen/projen#1059]
I was writing a JsiiProject which has a step to bundle a lambda zip via a docker build. I found the bundling step always failed in Github actions because of being not able to find the lambda source code.

After I did many experiments I found mounting volume inside a "jsii/superchain" container won't success. Below is an example:
 
```yaml
name: build
on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build-in-jsii:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      actions: write
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Run
        run: |-
          set -x
          docker version
          find .
          echo using delegated
          docker run --rm -u root -v $PWD:/ws/:delegated  \
          public.ecr.aws/sam/build-nodejs12.x bash -xc "cd /ws/ && find ."    ### 1. EMPTY IN /ws
          echo without delegated
          docker run --rm -u root -v $PWD:/ws/  \
          public.ecr.aws/sam/build-nodejs12.x bash -xc "cd /ws/ && find ."    ### 2. EMPTY IN /ws
    container:
      image: jsii/superchain
  
  build-on-host:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      actions: write
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Run
        run: |-
          set -x
          docker version
          find .
          docker run --rm -u root -v $PWD:/ws/:delegated  \
          public.ecr.aws/sam/build-nodejs12.x bash -xc "cd /ws/ && find ."    ### 3. /ws IS NOT EMPTY
```
1. `docker run -v ...` won't success in `jsii/superchain` container
2. `docker run -v ...` is successful on host

Here is the proof of concept https://github.com/wchaws/license-test/actions/runs/1225864526
