### ISSUE TITLE
The GH releaseWorkflowSetupSteps are inserted too late

### ISSUE THREAD

**Issue by mbonig** [projen/projen#1146]
I'm currently trying to use the releaseWorkflowSetupSteps to insert an upgrade to node:

```
      - uses: actions/setup-node@v2
        with:
          node-version: 14.18.1
```

to support eslint 5>

`error @typescript-eslint/eslint-plugin@5.0.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "10.24.1"`

The steps come too late in the process:

```
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn install --check-files --frozen-lockfile
      - name: Anti-tamper check
        run: git diff --ignore-space-at-eol --exit-code
      - name: Set git identity
        run: |-
          git config user.name "Automation"
          git config user.email "github-actions@github.com"
      - name: Bump to next version
        run: npx projen bump
      - uses: actions/setup-node@v2
        with:
          node-version: 14.18.1
```

Doesn't seem to be a way I can upgrade node before deps are installed.
