### ISSUE TITLE
mergify: Strict Mode Deprecation

### ISSUE THREAD

**Issue by neilkuan** [projen/projen#1502]
In this ci check, I got `The Mergify configuration is invalid`.

https://github.com/neilkuan/cdk-certbot-dns-route53/pull/199/checks?check_run_id=4758141003

Strict Mode Deprecation
see this blog: https://blog.mergify.com/strict-mode-deprecation/

example:
```
pull_request_rules:
  - name: automatic merge
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=work-in-progress
      - check-success=ci-one
      - check-success=ci-two
    actions:
      merge:
        method: merge
        strict: smart
```

need to change like this:
```bash
queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=ci-one
      - check-success=ci-two

pull_request_rules:
  - name: automatic merge
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=work-in-progress
      - check-success=ci-one
      - check-success=ci-two
    actions:
      queue:
        method: merge
        name: default
```
