### ISSUE TITLE
GitLab: upper case variables are not supported

### ISSUE THREAD

**Issue by pgarbe** [projen/projen#1693]
Sometimes variables needs to be upper case (e.g AWS_REGION). In the GitLab configuration, the variables for jobs are rendered  as snake case and it does not respect to original formatting. But it works for global variables.

How to reproduce:

```ts
const gitLabCiConfig = new pj.gitlab.GitlabConfiguration(project, {
    jobs: {
        build: {
            // does not work, renders lower case aws_region
            variables: { AWS_REGION: 'eu-central-1' },
            ...
        },
    },
});

// works
gitLabCiConfig.addGlobalVariables({
    AWS_REGION: 'eu-central-1',
});
```

This renders:

```yaml
variables:
  AWS_REGION: eu-central-1
build:
  variables:
    aws_region: eu-central-1
```
