### ISSUE TITLE
CodeArtifact Role Assumption not producing correct workflow

### ISSUE THREAD

**Issue by jessebye** [projen/projen#1843]
When attempting to use a CodeArtifact NPM registry and assume a role, the generated release workflow still tries to use the Access key ID / Secret access key:

```
      - name: Release
        run: npx -p publib@latest publib-npm
        env:
          NPM_DIST_TAG: latest
          NPM_REGISTRY: my-domain.d.codeartifact.us-east-2.amazonaws.com/npm/npm/
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

Here is the projen config being used:
```
import { cdk8s } from "projen";
const project = new cdk8s.ConstructLibraryCdk8s({
  ...
  codeArtifactOptions: {
    roleToAssume: "arn:aws:fake"
  },
  npmRegistryUrl: "https://my-domain.d.codeartifact.us-east-2.amazonaws.com/npm/npm/",
```

I tried to look in the code to see why this might be happening, but couldn't immediately identify any problem.

**Comment by Chriscbr** [comment]
Sounds like a possible bug.

@AminFazlMondo @charliehart-mondo can you take a look?

**Comment by AminFazlMondo** [comment]
I think this is the expected behaviour as the role assumption command, needs to have `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to assume the role, and then will override them and also set the session token.
https://github.com/cdklabs/publib/blob/ef1aa5a52f4c74829e2a49d8fd104ba665b55027/bin/publib-npm#L30

Also, we are using similar projen project but our release code is similar to below. are you missing the `AWS_ROLE_TO_ASSUME` @jessebye 

```
      - name: Release
        run: npx -p publib@latest publib-npm
        env:
          NPM_DIST_TAG: latest
          NPM_REGISTRY: my-domain.d.codeartifact.us-east-2.amazonaws.com/npm/npm/
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ROLE_TO_ASSUME: arn:aws:fake
```
