### ISSUE TITLE
Feature request: enable more easily pushing to AWS CodeArtifact

### ISSUE THREAD

**Issue by phitoduck** [projen/projen#2068]
Hi there,

I'm currently trying to create a `projen` setup for publishing multi-language AWS CDK constructs to AWS CodeArtifact. I believe that the `awscdk-construct` (and any other JSII projects) do not support this in a way that is satisfying for production. I think it's possible to fix this. Here's what I mean:

AWS instructs you to run this command to configure twine with an authentication token. The issue is: the max lifespan of this token is 12 hours. This means that you would have to manually place a new auth token into the GitHub secret every day if you wanted to use CodeArtifact as the PyPI/npm backend.

```bash
aws codeartifact get-repository-endpoint \
        --domain ai-package-index \
        --domain-owner $MY_ACCOUNT \
        --repository some-package-index-name \
        --format pypi \
        --query repositoryEndpoint \
        --output text
```

Sadly, `projen` is currently only able to use a `TWINE_PASSWORD` that is set in a GitHub secret. This is how you go about it:

```javascript
// .projenrc.js
...
publishToPypi: {
    twineUsernameSecret: "TWINE_USERNAME",
    twinePasswordSecret: "TWINE_PASSWORD",
    twineRegistryUrl: "my-aws-codeartifact-registry.com",
}
```

Which results in the following `.github/release.yml`:

```yaml
# .github/release.yml
...
- name: Release
        run: npx -p publib@latest publib-pypi
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
```

According to the [`publib` README](https://www.npmjs.com/package/publib), `publib` is actually capable of accepting `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` as environment variables to publish to CodeArtifact, *but only for npm*.

Where Python is concerned:

I was able to find the [section of code in `src/release/publisher.ts`](https://github.com/projen/projen/blob/main/src/release/publisher.ts#L436-L461) that deals with this.

```javascript
{
env: {
          TWINE_REPOSITORY_URL: options.twineRegistryUrl,
        },
        workflowEnv: {
          TWINE_USERNAME: secret(
            options.twineUsernameSecret ?? "TWINE_USERNAME"
          ),
          TWINE_PASSWORD: secret(
            options.twinePasswordSecret ?? "TWINE_PASSWORD"
          ),
        },
}
```

Would it be possible to add a config option to `.projenrc.js` such as this?

```javascript
...
publishToPypi: { 
     backend: "aws-code-artifact",
     aws_access_key_secret: "CODE_ARTIFACT__AWS_SECRET_ACCESS_KEY",
     aws_access_key_id_secret: "CODE_ARTIFACT__AWS_ACCESS_KEY_ID",
     codeArtifactDomain: "my-code-artifact-repository",
     twineRegistryUrl: "my-code-artifact-repository",
}
...
``` 

The idea is that instead of using `publib`, the `release.yml` would contain:

```yaml
- name: Release
        run: |
          # fetch a twine password from AWS and configure the twine CLI
          AWS_ACCOUNT=`aws sts get-caller-identity --query 'Account' --output text`
          aws codeartifact get-authorization-token --domain $CODE_ARTIFACT_DOMAIN --domain-owner $AWS_ACCOUNT --query authorizationToken --output text

          # publish the packages
          twine upload dist/python/*
        env:
          TWINE_USERNAME: aws
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CODE_ARTIFACT__AWS_SECRET_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CODE_ARTIFACT__AWS_ACCESS_KEY_ID }}
          TWINE_REPOSITORY_URL: my-code-artifact-repository.com
          CODE_ARTIFACT_DOMAIN: my-code-artifact-repository
```

I'm not a TypeScript dev so I worry this would be hard for me. However, I believe the approach here is viable. Would this change be acceptable?
