### ISSUE TITLE
publish to npm workflow fails when set project package manager to PNPM

### ISSUE THREAD

**Issue by huaxk** [projen/projen#2078]
The 'publish to npm' workflow fails when set project package manager to PNPM, it stops when install dependencies. 

```
Run cd .repo && pnpm i --frozen-lockfile
/home/runner/work/_temp/17ae009a-608e-489b-add9-6d21d8409601.sh: line 1: pnpm: command not found
Error: Process completed with exit code 127.
```

projen generates the following workflow code：

```
name: release
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
   ...
  release_npm:
    name: Publish to npm
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: needs.release.outputs.latest_commit == github.sha
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: dist
      - name: Prepare Repository
        run: mv dist .repo
      - name: Install Dependencies
        run: cd .repo && pnpm i --frozen-lockfile
      - name: Create js artifact
        run: cd .repo && npx projen package:js
      - name: Collect js Artifact
        run: mv .repo/dist dist
      - name: Release
        run: npx -p publib@latest publib-npm
        env:
          NPM_DIST_TAG: latest
          NPM_REGISTRY: registry.npmjs.org
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

There may not be pnpm/action-setup?
