### ISSUE TITLE
github actions: cannot add multiple labels as array to get the correct runner

### ISSUE THREAD

**Issue by pharindoko** [projen/projen#2226]
When I add in .projenrc.js file  for a cdk-typescript-app following values for the `workflowRunsOn` property

```javascript
const project = new awscdk.AwsCdkTypeScriptApp({
  cdkVersion: '2.1.0',
  defaultReleaseBranch: 'main',
  name: 'cdk-project-test',
  workflowRunsOn: ["self-hosted", "testrunner"],
  },
);
```

following values will be attached to .github/workflows/build.yml and no runner will be attached when this is executed:
```yml

name: build
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on:
      - self-hosted
      - testrunner
```

No runner is called as the runner would expect labels self-hosted + testrunner

What is my expectation ?

```yml
name: build
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: [self-hosted, testrunner]
```

this requests a runner having both labels...

br,

flo
