### ISSUE TITLE
GitLab job names are not preserved

### ISSUE THREAD

**Issue by robert-affinidi** [projen/projen#2315]
### Problem

Default `.gitlab-ci.yml` generation does not preserve job names which blocks using hidden (starting with a dot) [GitLab jobs](https://docs.gitlab.com/ee/ci/jobs/index.html#hide-jobs).

Here is the code snippet for GitLab config:

```ts
const { gitlab } = require('projen')

new gitlab.GitlabConfiguration(project, {
  jobs: {
    'external-include': {
      stage: 'new-stage',
    },
    '.my-cache': {
      script: [
        'echo Here goes caching',
      ],
    },
    'my-job': {
      extends: [
        '.my-cache',
      ],
      script: [
        'echo Here is my-job, no, my_job',
      ],
    },
  },
});
```
### Current Results

Here are the current results:

```yaml
# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

stages:
  - new-stage
external_include:
  stage: new-stage
_my_cache:
  script:
    - echo Here goes caching
my_job:
  extends:
    - .my-cache
  script:
    - echo Here is my-job
```

### Expected Results

```yaml
# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

stages:
  - new-stage
external-include:
  stage: new-stage
.my-cache:
  script:
    - echo Here goes caching
my-job:
  extends:
    - .my-cache
  script:
    - echo Here is my-job

```

### Proposed Solution

Add new option to disable default job name snaking, like:

```ts
const { gitlab } = require('projen')

new gitlab.GitlabConfiguration(project, {
  snakeJobNames: false,
  jobs: {
    ...
```

**Comment by robert-affinidi** [comment]
You can use dots freely AFAIR. The reason for `snaking` keys is probably due some mapping for keywords, like `beforeScript` => `before_script`.

**Comment by robert-affinidi** [comment]
Here is the PR with the fix proposal : https://github.com/projen/projen/pull/2316

**Comment by mrgrain** [comment]
Hey thanks for the proposed fix. Not sure if I'm convinced of the additional property. Wouldn't we want to always allow a dot as the first character or have an optional `hidden` property on each job?!

**Comment by mrgrain** [comment]
Background:

If the generic snaking has a good reason, disabling to allow another valid feature feels like a bad fix.

If the reason for snaking is locally limited, but not needed otherwise, we should strive to contain it the required use case.

**Comment by robert-affinidi** [comment]
I would remove snaking from job names at all as it leads to behaviour like:
```
_my_cache:
  script:
    - echo Here goes caching
my_job:
  extends:
    - .my-cache
```
(job name was changed to `_my_cache` but the ref in `extends` is not).
I presume the reason for snake was to handle cases like [beforeScript](https://github.com/projen/projen/blob/main/src/gitlab/configuration-model.ts#L270) which shall be translated to Gitlab's [before_script](https://docs.gitlab.com/ee/ci/yaml/#before_script).
