### ISSUE TITLE
GitLab: generated `.gitlab-ci.yml` is invalid if I add cobertura report for `GitlabConfiguration`

### ISSUE THREAD

**Issue by kerilb** [projen/projen#2372]
Generated `.gitlab-ci.yml` template is invalid since GitLab introduced new YAML structure for job reports.

Current behavior:
``` js
#JS
artifacts: {
   reports: {
      cobertura: 'coverage/cobertura-coverage.xml',
   }
}
```
compile as:

``` yaml
#YAML
artifacts:
  reports:
    cobertura: coverage/cobertura-coverage.xml
```

Expected behavior:
something like
``` js
#JS
artifacts: {
   reports: {
      coverage_report: {
        coverage_format: 'cobertura',
        path: 'coverage/cobertura-coverage.xml',
      }
   }
}
```
to be
``` yaml
#YAML
artifacts:
  reports:
    coverage_report:
      coverage_format: cobertura
      path: coverage/cobertura-coverage.xml
```

Actual reports structure [https://docs.gitlab.com/ee/ci/yaml/artifacts_reports.html](https://docs.gitlab.com/ee/ci/yaml/artifacts_reports.html)
