### ISSUE TITLE
DockerCompose doesn't support networks

### ISSUE THREAD

**Issue by KennethWussmann** [projen/projen#2397]
Hey,

it's currently not possible to define networks in a `docker-compose.yml` using the [`DockerCompose` component](https://github.com/projen/projen/blob/main/src/docker-compose.ts#L43).

Example `docker-compose.yml`:
```YAML
version: "3.7"
services:
  busybox:
    image: busybox
    networks:
      - traefik

networks:
  traefik:
    external: true
```

Definition in projen:
```typescript
import { DockerCompose } from 'projen';

const dockerCompose = new DockerCompose(project);
dockerCompose.addService('busybox', {
  image: 'busybox',
  // not available:
  // networks: ['traefik'],
})// .addNetwork('traefik', ...);
```

I'm happy to help with a PR, once I know I didn't miss anything 😄 

Thanks! I really like the `DockerCompose` support.
