### ISSUE TITLE
python: Poetry dependency metadata doesn't render in pyproject.toml correctly

### ISSUE THREAD

**Issue by cogwirrel** [projen/projen#2601]
The section in the Python README called ["Poetry Dependencies"](https://github.com/projen/projen/blob/main/docs/python.md#poetry-dependencies) mentions that you can specify metadata in the "version" part of the dependency:

> Dependencies that require additional metadata regarding extras etc. may be declared as follows:

```
deps: [
  ...
  "mypackage@{version = '^3.3.3', extras = ['mypackage-extra']}",
],
```

However when I do this, the resulting `pyproject.toml` file ends up like:

```toml
  [tool.poetry.dependencies]
  mypackage = "{version = '^3.3.3', extras = ['mypackage-extra']}"
  python = "^3.7"
```

This is un-parseable by poetry, which gives the error:

`Could not parse version constraint: {version`

I'm wondering if this ever worked? I can't see any unit tests covering this functionality mentioned in the README :)

To reproduce with a minimal example, you can do:

1. `npx projen new python --poetry`
2. Add `deps=["mypackage@{version = '^3.3.3', extras = ['mypackage-extra']}"]` to `.projenrc.py`
3. `npx projen` - notice the `poetry env use python` command fails as the version can't be parsed

**Comment by mrgrain** [comment]
Do you know what a correct version of this should look like?

**Comment by cogwirrel** [comment]
Most examples online use the inline syntax like:

```toml
[tool.poetry.dependencies]
mypackage = {version = "^3.3.3", extras = ["mypackage-extra"]}
```

But I've been playing around and this is also valid:

```toml
[tool.poetry.dependencies]
[tool.poetry.dependencies.mypackage]
version = "^3.3.3"
extras = ["mypackage-extra"]
```

I've been playing with projen locally and I think it can be fixed by trying to parse the version as toml first, and if it parses just passing that to the `TomlFile` which can stringify it back as the object :)

Will raise a PR shortly :)
