### ISSUE TITLE
`workflowPackageCache` doesn't work with `pnpm`

### ISSUE THREAD

**Issue by riywo** [projen/projen#2710]
Follow up of https://github.com/projen/projen/pull/2709

Because "Setup Node.js" step runs before "Setup pnpm" step, it fails with:

```
Error: Unable to locate executable file: pnpm. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

Need to shuffle the order of the steps.

**Comment by riywo** [comment]
https://pnpm.io/continuous-integration

```
name: pnpm Example Workflow
on:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [15]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
```
