### ISSUE TITLE
Feature Request: Specify GitHub Runners by name

### ISSUE THREAD

**Issue by rami-husein** [projen/projen#2814]
[Relevant GitHub Blog Post.
](https://github.blog/changelog/2022-11-01-github-actions-restrict-workflows-to-specific-runners-using-runner-group-names/)

Currently, the properties: `workflowRunsOn`, `githubOptions.pullRequestLintOptions.runsOn`, `depsUpgradeOptions.workflowOptions.runsOn`, `autoApproveOptions.runsOn`, `staleOptions.runsOns`, accessible in `.projenrc.ts`, accepts a list of strings; GitHub Runner labels. While this does allow _some_ Runner targeting, some teams or organizations may want to target Runners by their Runner Group. For example, Runner Groups may correspond to an specific clusters, environments, or teams, and labels alone may be insufficient.

GitHub introduced the ability to target Runners using Runner Group names (aforementioned blog post). 

Feature Example:
`.projenrc.ts`

```typescript
  workflowRunsOn: {
    group: "Default",
    labels: ["self-hosted", "Linux", "x64"],
  }
```
would render
```yaml
jobs:
  build:
    runs-on:
      group: Default
      labels:
        - self-hosted
        - Linux
        - x64
```
