### ISSUE TITLE
Add support for Gitlab multiple caches

### ISSUE THREAD

**Issue by daraghosullivan** [projen/projen#3022]
Thank you for the amazing work, I am a big fan of projen.

I have noticed a slight gap in the gitlab model.

Support for multiple caches were introduced in GitLab 13.10, see [here](https://docs.gitlab.com/ee/ci/caching/index.html#use-multiple-caches).

Currently the `Job` model only supports type `Cache` for the value `cache`, see [here](https://github.com/projen/projen/blob/75283194163716080f2c75a40f5b5b934f3c9dee/src/gitlab/configuration-model.ts#L310-L311).

Therefore we cannot support a job like:
```
test-job:
  stage: build
  cache:
    - key:
        files:
          - Gemfile.lock
      paths:
        - vendor/ruby
    - key:
        files:
          - yarn.lock
      paths:
        - .yarn-cache/
```

I plan to contribute and fix this gap myself, I am just opening this issue for visibility.
