### ISSUE TITLE
Add support for Gitlab trigger:forward keyword

### ISSUE THREAD

**Issue by daraghosullivan** [projen/projen#3327]
I have noticed another slight gap in the gitlab model.

The `trigger:forward` keyword has been [generally available](https://gitlab.com/gitlab-org/gitlab/-/issues/355572) in GitLab since 15.1.

Currently the `Trigger` model does not include any property for `forward`, see [here](https://github.com/projen/projen/blob/295e186a6df724cecf3dae142429af89b77d02a7/src/gitlab/configuration-model.ts#L567-L581).

Therefore we cannot support a job like:
```
test-job:
  stage: build
  trigger:
    project: example-group/example-project
    forward:
      pipeline_variables: false
      yaml_variables: false
```

I plan to contribute and fix this gap myself, I am just opening this issue for visibility.
