### ISSUE TITLE
!reference tag in gitlab job scripts will be rendered in quotes

### ISSUE THREAD

**Issue by JohannesKonings** [projen/projen#3590]
Using the [!reference](https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#reference-tags) tag will be rendered in quotes.

```typescript
 const job: Job = {
      extends: ['.release'],
      beforeScript: ['!reference [.release, beforeScript]', 'npm install'],
    };
   return {
      release: job,
    };
```
```yaml
release:
  extends:
    - .release
  before_script:
    - "!reference [.setup, script]"
    - npm install
```

Due to the quotes the gitlab pipeline doesn't merge the reference.

Presumply the used YamlFile needs a custom tag to recognise `!reference`: https://github.com/projen/projen/blob/main/src/gitlab/configuration.ts#L156
https://eemeli.org/yaml/#writing-custom-tags
