### ISSUE TITLE
[BUG] release workflows breaking for sub-projects, after fix introduced in #3821

### ISSUE THREAD

**Issue by bweigel** [projen/projen#3837]
### Describe the bug

After upgrading Projen in my [@aws-pdk monorepo](https://aws.github.io/aws-pdk/developer_guides/monorepo/index.html) the release workflows of subprojects fail during the step `Publish to NPM..Create js artifact`.

### Expected Behavior

The release workflows of subprojects will still work.

### Current Behavior

During the release workflow steps `release_npm`, the `package.json` of the root module is overwritten by the submodules release artifacts (`dist/js/*.tgz` is extracted into the temporary `.repo`) and breaks the old behavior (where everything was copied over):

### Reproduction Steps

Check out the minimal working example: https://github.com/bweigel/projen_multiproject_release_mwe
Specifically [this commit](https://github.com/bweigel/projen_multiproject_release_mwe/commit/b04ce685fc421d38670737dff812a81c920982e2), where the release is still broken.

### Additional Information/Context

Minimal working example: https://github.com/bweigel/projen_multiproject_release_mwe

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

Manjaro Linux, NodeJS v18.20.4, Projen 0.87.2

**Comment by bweigel** [comment]
## Idea :bulb: 

Now, what has me puzzled is this: _Do we actually need all of the steps currently in `release_npm`?_ Specifically these:

```yaml
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: .repo
      - name: Install Dependencies
        run: cd .repo && yarn install --check-files --frozen-lockfile
      - name: Extract build artifact
        run: tar --strip-components=1 -xzvf dist/js/*.tgz -C .repo
      - name: Move build artifact out of the way
        run: mv dist dist.old
      - name: Create js artifact
        run: cd .repo && npx projen package:js
      - name: Collect js artifact
        run: mv .repo/dist dist
```

We already have built the releasable/publishable artifact in the `release` step of the workflow. But we copy it into the publish step and build it again?! Why? I was wondering, if we could just remove all the steps above to make this step faster and remove waste.

I have tried this out (see commit https://github.com/bweigel/projen_multiproject_release_mwe/commit/a2b5d86cf4395e78a487bd2ee14c24b381f0efec) and it seems to work, but I am sure I am missing something here...
