### ISSUE TITLE
Unable to set a GitHub job's runs-on to a string

### ISSUE THREAD

**Issue by scottschreckengaust** [projen/projen#3908]
Unable to set a job's `run-on` with a `string`:

```yaml
name: matrix-workflow
on:
  workflow_dispatch: {}
  jobs:
    matrix-job:
      name: matrix-job
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os:
            - ubuntu-latest
            - macos-latest
            - windows-latest
```

The [`jobs.<job_id>.runs-on`](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on) can take a `string | string[]`

**Comment by scottschreckengaust** [comment]
Found a solution to `JsonPatch` from [example within Projen](https://github.com/projen/projen/blob/38be291c30f131eba6b58e2b79b9865eebe4ae2e/projenrc/windows-build.ts#L71):

```typescript
import { JsonPatch } from 'projen';
import { NodeProject } from 'projen/lib/javascript';
import { Job, JobPermission, } from 'projen/lib/github/workflows-model';

const workflowName = 'matrix-workflow';
const jobName = 'matrix-job';

export function gitHubMatrixWorkflow(project: NodeProject) {
    if (project.github) {
        const os: string[] = ['ubuntu-latest', 'macos-latest', 'windows-latest', ];
        const job: Job = {
            name: jobName,
            runsOn: os,
            strategy: {
                failFast: false,
                matrix: {
                    domain: {
                        os: os,
                    },
                },
            },
            permissions: {
                contents: JobPermission.NONE,
            },
            steps: [
                {
                    name: 'Setup Node',
                    uses: 'actions/setup-node@v4',
                },
                {
                    name: 'Report the Architecture and number of CPUs',
                    run: [
                        'echo "OS: \${{ matrix.os }}"',
                        'node -e \'console.log(`Architecture: ${process.arch}`)\'',
                    ].join('\n'),
                },
            ],
        };

        const workflow = project.github.addWorkflow(workflowName);
        if (workflow) {
            workflow.on({
                workflowDispatch: {},
            });
            workflow.addJob(jobName, job);

            // Patch the `runs-on` with ${{ matrix.os }} when available
            if (job.strategy?.matrix?.domain?.os && workflow.file) {
                workflow.file?.patch(
                    JsonPatch.add(`/jobs/${jobName}/runs-on`, '${{ matrix.os }}'),
                );
            }
        }     
    }
};
```

resulted in
```yaml
# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".

name: matrix-workflow
on:
  workflow_dispatch: {}
jobs:
  matrix-job:
    name: matrix-job
    runs-on: ${{ matrix.os }}
    permissions:
      contents: none
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Report the Architecture and number of CPUs
        run: |-
          echo "OS: ${{ matrix.os }}"
          node -e 'console.log(`Architecture: ${process.arch}`)'
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
```

**Comment by mrgrain** [comment]
> The [jobs.<job_id>.runs-on](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on) can take a string | string[]

@scottschreckengaust For my understanding, why can we not provide this as a list if one string? Seems to me that `string` is a less generalized subset of `string[]`!?

**Comment by janwvjaarsveld** [comment]
@mrgrain I have a similar issue, when trying to set a value for `strategy -> matrix`, using the domain property as string value.

[Following this example](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#example-using-contexts-to-create-matrices):
```
on:
  repository_dispatch:
    types:
      - test
 
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ github.event.client_payload.versions }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
```
Since the `domain` property is of type `Record<string, JobMatrixValue[]>`, I need to define it as 
```
            strategy: {
                matrix: { domain: { version: ['${{ github.event.client_payload.versions }}'] } },
            },
```

Which then becomes:
```
    strategy:
      matrix:
        version:
          - ${{ github.event.client_payload.versions }}
```
Instead of:
```
    strategy:
      matrix:
        version: ${{ github.event.client_payload.versions }}
```
Should the type of domain perhaps become `Record<string, JobMatrixValue | JobMatrixValue[]>`, or how else can I achieve this?
