### ISSUE TITLE
GitLab pipeline .gitlab-ci.yml analogues to package.json as an hybrid file

### ISSUE THREAD

**Issue by JohannesKonings** [projen/projen#3984]
Renovate can also update GitLab CI templates versions like npm dependencies: https://docs.renovatebot.com/modules/manager/gitlabci/

```yaml
include:
- project: ABC/XYZ
  file: /template.yaml
  ref: 1.0.0
...
```

For that it would be helpfull if projen can handle a template version like a npm dependencies, so that will not overwritten if renovate update that version.
