### ISSUE TITLE
Release workflow does not use projenCredentials

### ISSUE THREAD

**Issue by yamshionamz** [projen/projen#4056]
Hi, I am developing CDK project using below
```
const project = new awscdk.AwsCdkTypeScriptApp({
  // ...
  release: true,
  projenCredentials: github.GithubCredentials.fromApp({
    appIdSecret: "XXX_APP_ID",
    privateKeySecret: "XXX_PRIVATE_KEY",
  }),
```

While generated build and upgrade workflows use above credentials, release workflow does not
```
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.sha }}
        run: errout=$(mktemp); gh release create $(cat dist/releasetag.txt) -R $GITHUB_REPOSITORY -F dist/changelog.md -t $(cat dist/releasetag.txt) --target $GITHUB_REF 2> $errout && true; exitcode=$?; if [ $exitcode -ne 0 ] && ! grep -q "Release.tag_name already exists" $errout; then cat $errout; exit $exitcode; fi
```

Expected behavior -> Add step to generate token in the beginning and use it in later steps
```
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a
        with:
          app_id: ${{ secrets.XXX_APP_ID }}
          private_key: ${{ secrets.XXX_PRIVATE_KEY }}
```
