### ISSUE TITLE
Adding setup steps for github_release job

### ISSUE THREAD

**Issue by yamshionamz** [projen/projen#4057]
I use shared runners to run `release` workflow. In order to install gh command, I added steps to `releaseWorkflowSetupSteps`.

```
const project = new awscdk.AwsCdkTypeScriptApp({
  release: true,
  releaseWorkflowSetupSteps: [
    {
      name: "Setup Python",
      uses: "actions/setup-python@v5",
      with: {
        "python-version": "3.13",
      },
    },
    {
      name: "Setup GitHub CLI",
      uses: "ksivamuthu/actions-setup-gh-cli@v3",
    },
  ],
  workflowRunsOn: ["shared-runners"],
  // ...
}
```

However, it adds the setup steps to `release` job but not to `github_release` job, which requires gh command.

```yaml
jobs:
  release:
    runs-on: shared-runners
    permissions:
      contents: write
    outputs:
      latest_commit: ${{ steps.git_remote.outputs.latest_commit }}
      tag_exists: ${{ steps.check_tag_exists.outputs.exists }}
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set git identity
        run: |-
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Setup GitHub CLI
        uses: ksivamuthu/actions-setup-gh-cli@v3

  # Not added to release_github job which requires gh
  release_github:
    name: Publish to GitHub Releases
    needs: release
    runs-on: shared-runners
```

Is there way to add setup steps for `release_github` job? Thanks
