### ISSUE TITLE
Issue setting dynamic matrix strategy values from context

### ISSUE THREAD

**Issue by janwvjaarsveld** [projen/projen#4130]
@mrgrain I have a similar issue, when trying to set a value for `strategy -> matrix`, using the domain property as string value.

[Following this example](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#example-using-contexts-to-create-matrices):
```
on:
  repository_dispatch:
    types:
      - test
 
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ github.event.client_payload.versions }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
```
Since the `domain` property is of type `Record<string, JobMatrixValue[]>`, I need to define it as 
```
            strategy: {
                matrix: { domain: { version: ['${{ github.event.client_payload.versions }}'] } },
            },
```

Which then becomes:
```
    strategy:
      matrix:
        version:
          - ${{ github.event.client_payload.versions }}
```
Instead of:
```
    strategy:
      matrix:
        version: ${{ github.event.client_payload.versions }}
```
Should the type of domain perhaps become `Record<string, string | JobMatrixValue[]>`, or how else can I achieve this?
