### ISSUE TITLE
Release is blocked if branch protection is enabled

### ISSUE THREAD

**Issue by wchaws** [projen/projen#572]
I want to enforce each PR/commit is reviewed before merging. So I enabled Github branch protection rule.
However, I find `projen` release workflow will push a commit automatically which is against the branch protection rule.

Below is the workflow:
https://github.com/aws-samples/cdk-keycloak/runs/1976482226?check_suite_focus=true

```
git push origin $BRANCH
  shell: sh -e {0}
  env:
    CI: true
    BRANCH: refs/heads/main
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: At least 1 approving review is required by reviewers with write access.        
To https://github.com/aws-samples/cdk-keycloak
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/aws-samples/cdk-keycloak'
Error: Process completed with exit code 1.
```

**Comment by pahud** [comment]
Hi, just a little context for this.

We enabled the github branch protection and enforce at least one review approval before the merge. However, we noticed that the `release` workflow generated by projen will try `git push origin` in its workflow, which is forbidden by the protection rule.

Wondering is there any better workaround for this?

https://github.com/aws-samples/cdk-keycloak/blob/c7048085f510cfd9625b597a0dd0f26dd0d00aae/.github/workflows/release.yml#L35-L38

**Comment by eladb** [comment]
Let's change how we do releases, because branch protection is very important for security reasons. Here's a design sketch (feedback is more than welcome of course):

Since we want automated releases, we need to move out the _current version_ and the _changelog_ from within the repository so a commit will not be required in order to bump and release an new version. To that end, we will simply use **GitHub Releases** and git tags to record the current version and publish release notes.

Basically this means that we need to modify the `release` workflow to create a GitHub Release instead of pushing the commit+tag to the repo. This should be possible since the release workflow is triggered by `push` and has read/write permissions.

The bump process will need to determine the version of the project by finding the latest `vX` tag and then updating `package.json` to include the new version. This means the whole notion of the `version.json` file goes away. I am wondering if we can just omit the `version` field from the checked-in `package.json`. Not sure what the implications are...

**Comment by Chriscbr** [comment]
@eladb Your plan makes sense, although removing changelogs from version control is an unfortunate drawback. Also I doubt you can remove the version field from `package.json`, so updating files for releases seems hard to avoid. I'm wondering if there are any other ways to resolve this (maybe you've considered some of these already):

- Is it possible to have the workflow automatically create a pull request instead of pushing directly, and then auto-approve said PR (maybe with an automerge label, or by calling a REST API endpoint)?
- Would creating a separate "release" branch (and applying different release protection rules) solve any of these issues?
- Is it possible to set the release flow to be run with a custom bot user with limited admin privileges (i.e. no repo deletion) to bypass the branch protection rules? This would require the branch protection rules to be set to not apply to administrators.

Thoughts?

**Comment by eladb** [comment]
@Chriscbr Good points.

> Is it possible to have the workflow automatically create a pull request instead of pushing directly, and then auto-approve said PR (maybe with an automerge label, or by calling a REST API endpoint)?

This will introduce a race condition on "main". If a commit is merge between the time the PR was created and the time it's merged, the version will include this change but it will not be accounted for in the changelog. This is probably not an issue for small projects but when traffic on "main" grows, it can be an issue.

> Would creating a separate "release" branch (and applying different release protection rules) solve any of these issues?

This is possible but slightly cumbersome. This is the model we use in the CDK. It requires back-merging from the release branch after every release, which is more automation, and if there is branch protection, you'll need a dedicated auto-approve workflow...

> Is it possible to set the release flow to be run with a custom bot user with limited admin privileges (i.e. no repo deletion) to bypass the branch protection rules? This would require the branch protection rules to be set to not apply to administrators.

I rather not require every project to install another secret.

---

The proposed model basically manages version information only through git tags which is actually a pretty common model. E.g Go modules use git tags to indicate module version.

It's also a more robust model than what we have today because there's a single source of truth (today we need maintain both tags and a version file in sync).

It will also allow us to cleanly decouple "main" builds and publishing the release. We can say that the main build creates a GitHub release+tag at the end of the build and uploads the build artifact in there. 

The publishing workflow(a) are triggered when a new release/tag is created. They download the artifact and publish to the respective package manager.

**Comment by polothy** [comment]
You might be able to accomplish these goals with [Semantic Release](https://semantic-release.gitbook.io/semantic-release/).  I'm not 100% sure though, never used it personally on a project, but seems popular enough.

There is also this project: https://github.com/conventional-changelog/releaser-tools

I customized our release workflow and it addresses a couple of your goals

- Create GitHub release with release notes.
- Does not release when there are only `chore` commits.
- BUT, still does the same git commit/tag/push, but I do that because that's how it's done now.

Here is my workflow:

```yaml
name: Release

on:
  push:
    branches:
      - main

env:
  GIT_AUTHOR_NAME: github-actions[bot]
  GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
  GIT_COMMITTER_NAME: GitHub
  GIT_COMMITTER_EMAIL: noreply@github.com
  CI: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determine if release is created or not
        id: release
        run: ./hack/check_if_release.sh

      - run: yarn install --check-files --frozen-lockfile

      - name: Anti-tamper check
        run: npx projen && git diff --exit-code

      - name: Bump to next version
        run: npx projen bump

      - name: Build
        run: npx projen build

      - name: Anti-tamper check
        run: git diff --exit-code

      - id: tag
        run: ./hack/read_tag.sh

      - name: NPM publish
        if: steps.release.outputs.create == '1'
        run: ./hack/npm-publish.sh

      - name: PyPi publish
        if: steps.release.outputs.create == '1'
        run: ./hack/pypi-publish.sh

      - name: Push commits and tags
        if: steps.release.outputs.create == '1'
        run: git push origin main && git push --follow-tags origin main

      - name: GitHub release notes
        id: body
        run: ./hack/release_notes.sh

      - name: Create GitHub release
        uses: actions/github-script@v3
        if: steps.release.outputs.create == '1'
        env:
          TAG_NAME: ${{ steps.tag.outputs.name }}
          BODY_PATH: ${{ steps.body.outputs.path }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            body = fs.readFileSync(process.env.BODY_PATH, { encoding: 'utf8' });
            await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: process.env.TAG_NAME,
              tag_name: process.env.TAG_NAME,
              body: body
            })
```

Contents of `hack/check_if_release.sh`:

```bash
#!/usr/bin/env bash

# Enable stricter Bash http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# Requires Go 1.16
go install github.com/caarlos0/svu@v1.2.0

# Ensure its installed and available
command -v svu

create="1"
if [ "$(svu next)" = "$(svu current)" ]; then
  create="0"
fi

echo "current: $(svu current)"
echo "next:    $(svu next)"
echo "::set-output name=create::${create}"
```

Contents of `hack/read_tag.sh`:

```bash
#!/usr/bin/env bash

# Enable stricter Bash http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# Ensure its installed
command -v jq

version=$(jq --raw-output .version version.json)

if [ -z "$version" ]; then
  echo "::error::Failed to read version from version.json"
  exit 1
fi

echo "::set-output name=name::v${version}"
```

Contents of `hack/release_notes.sh`:

```bash
#!/usr/bin/env bash

# Enable stricter Bash http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# The tail removes the header line with the release version and date, which is redundant for GitHub release body
npx conventional-changelog --release-count 2 --preset conventionalcommits | tail -n +2 > github_release_notes.md
cat github_release_notes.md
echo "::set-output name=path::$(pwd)/github_release_notes.md"
```

So, likely the most controversial part of all this is the use of `svu`.  It's yet another tool to determine next git tag based on conventional commits, but by default, it doesn't suggest a new tag if all the commits since the last release are `chore` commits.  Maybe semantic release has a way to configure release behavior like this.  Sounds hacky, but I suppose you could check to see if the generated change log is basically empty?

Anyways, just thought I'd share, see if it inspired anything.  Would be nicer if there was something that we could get "off the shelf" that would just handle this sort of release workflow for us vs mixing and hacking tools together.

> The publishing workflow(a) are triggered when a new release/tag is created. They download the artifact and publish to the respective package manager.

This sounds like a nice idea, especially if the workflow could be updated and re-tried.  I have had problems when working on the workflow where it would tag and push but fail to upload to package managers.
