### ISSUE TITLE
Enable awscdk-construct to dual build for cdk and monocdk

### ISSUE THREAD

**Issue by dontirun** [projen/projen#916]
I'm working on a construct that has both cdk v1 and monocdk users. Currently during a custom build process I swap out the `.projen.js` file and do some string replacements for a monocdk build

1. @aws-cdk and @aws-cdk/core -> monocdk
2. @aws-cdk/assert -> @monocdk-experiment/assert 

It would be nice to be able to do this natively

**Comment by dontirun** [comment]
I'm using GitLab to build this project. Including a snippet of my hacky workaround

``` yaml
build_monocdk:
  stage: build
  rules:
    - when: on_success
  script:
    # Install dependencies
    - yarn install --check-files --frozen-lockfile
    # setup for monocdk build
    - rm yarn.lock
    - rm .projenrc.js
    - mv .projenrc.monocdk.js .projenrc.js
    - find ./src -type f | xargs sed -i  's,@aws-cdk/core,monocdk,g'
    - find ./test -type f | xargs sed -i  's,@aws-cdk/core,monocdk,g'
    - find ./src -type f | xargs sed -i  's,@aws-cdk,monocdk,g'
    - find ./test -type f | xargs sed -i  's,@aws-cdk,monocdk,g'
    - find ./test -type f | xargs sed -i  's,monocdk/assert,@monocdk-experiment/assert,g'
    # Synthesize project files
    - npx projen
    - git config --global user.email gilab-runner@gitlab.com
    - git config --global user.name "Auto-bump"
    # compile and test
    - npm version --no-git-tag-version ${CI_COMMIT_TAG#v}
    - npx projen test
    - npx jsii --silence-warnings=reserved-word --no-fix-peer-dependencies
    - npx jsii-docgen
    - npx jsii-pacmak


```
